# Generated by Django 5.2.8 on 2025-11-25 01:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inicio', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='notebook',
            name='imagen',
            field=models.ImageField(null=True, upload_to='imagen_notebooks/'),
        ),
    ]
