# Generated by Django 5.2.8 on 2025-11-25 23:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inicio', '0002_notebook_imagen'),
    ]

    operations = [
        migrations.AddField(
            model_name='notebook',
            name='ram',
            field=models.CharField(default='Sin especificar', max_length=50),
        ),
    ]
